### ISSUE TITLE
KryoNetException: Error during deserialization. (But only sometimes)

### ISSUE THREAD

**Issue by orange451** [EsotericSoftware/kryonet#149]
When I connect to my server using TCP from my client and start sending data, SOMETIMES I get this error:

> Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:141)
	at com.esotericsoftware.kryonet.Client.update(Client.java:247)
	at com.esotericsoftware.kryonet.Client.run(Client.java:333)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 18
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:113)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:613)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:724)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:58)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:139)
	... 3 more

Sometimes when I run the application it works with no problem. Sometimes I am met with this error. I am not quite sure why. I know I am registering all the appropriate classes, as sometimes the application works without problem. Are there any suggestions anyone can give to help debug this?

**Comment by orange451** [comment]
Thanks for the reply, @crykn 
All of the objects I am sending only contain Long and String fields.

I will look into logging the readobject method, thanks for the suggestion.

[Edit]
I've updated to using a newer version of kryo. There's now debug output in the console. What appears to be happening is data is being sent before the client has registered their classes. Not quite sure how that is happening.

[Edit 2]
I changed my code so that I register my classes before I attempt to establish a connection. I believe this has fixed it.
