### ISSUE TITLE
Error during deserialization

### ISSUE THREAD

**Issue by eli-psis** [EsotericSoftware/kryonet#166]
I have a minecraft server 1.12.2 with Java8 an It sends this error and then it crashes and close the server. I don´t know how to fix it, could you help me please. 

[13:15:20] [Server/INFO] [STDOUT]: [com.esotericsoftware.minlog.Log$Logger:print:231]: 16:49  WARN: [kryonet] Error reading UDP from unregistered address: /162.55.232.105:40239
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
        at com.esotericsoftware.kryonet.UdpConnection.readObject(UdpConnection.java:89)
        at com.esotericsoftware.kryonet.Server.update(Server.java:281)
        at com.esotericsoftware.kryonet.Server.run(Server.java:372)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: |
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
        at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:55)
        at com.esotericsoftware.kryonet.UdpConnection.readObject(UdpConnection.java:83)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: |
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
        ... 8 more
Caused by: java.lang.NullPointerException

**Comment by crykn** [comment]
This is not the right place to look for support with your Minecraft server. Kryonet is a java networking library. Any issues you encounter aren't caused by KroNet, but rather one of the mods you are using. Try reporting this on their issue tracker/forum.
